Integrate cartridge to the bus and fix linking error caused by undefined reference to the Mapper's destructor.
Bus class:
- Integrate Cartridge class.

Base Mapper class:
- Fix deletion of children, even pure virtual destructors must be implemented.